import { createPagesFunctionHandler } from "@react-router/cloudflare";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore - the server build file is generated by `react-router build`
// eslint-disable-next-line import/no-unresolved
import * as build from "../build/server";

export const onRequest = createPagesFunctionHandler({ 
  // @ts-expect-error - React Router 7.6 build compatibility issue
  build,
  getLoadContext: (context) => ({ 
    cloudflare: context.context.cloudflare 
  })
});
